name: "Deploy to S3"
description: "Deploy a static website to S3"
runs:
  using: 'node20'
  # All paths below are relative
  # to reusable action file location
  #
  # pre: <-- script executed before
  main: 'dist/index.js'
  # post: <-- script executed after

